### ISSUE TITLE
点START 直接奔溃

### ISSUE THREAD

**Issue by xuezhenbo** [mightofcode/android-vpnservice#1]
E/QCNEJ: |QCNEJ/CndHalConnector| Failed to parse input for notifyDefaultNetworkChanged: java.lang.IllegalArgumentException: Unknown RatType:17
2020-07-14 12:56:59.464 20633-20814/com.mocyx.basic_client E/BioUdpHandler: error
    java.net.ConnectException: Network is unreachable
at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:466)
        at sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:779)
        at com.mocyx.basic_client.bio.BioUdpHandler.run(BioUdpHandler.java:174)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-07-14 12:56:59.490 1378-2838/? E/GnssLocationProvider: No APN found to select.
2020-07-14 12:56:59.492 1378-2838/? E/GnssLocationProvider: updateNetworkAvailability failed

**Comment by mightofcode** [comment]
好的 有空我会看下
